# Adds conversion webhook configuration to LLMInferenceServiceConfig CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: llminferenceserviceconfigs.serving.kserve.io
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: kserve-webhook-server-service
          namespace: opendatahub
          path: /convert
      conversionReviewVersions:
        - v1
        - v1beta1